# .goreleaser.yml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: provider
    main: ./main.go
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags: [-trimpath]
    ldflags:
      - "-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}"
    goos: [freebsd, windows, linux, darwin]
    goarch: [amd64, "386", arm, arm64]
    ignore:
      - goos: darwin
        goarch: "386"

archives:
  - id: zips
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
  extra_files:
    - glob: "dist/terraform-registry-manifest.json"
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"

# Sign only the checksum file (what you had)
signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  # Keep attaching your Terraform Registry manifest to the release
  extra_files:
    - glob: "dist/terraform-registry-manifest.json"
      name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"
  draft: false
  prerelease: auto

changelog:
  disable: true
